# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fast_typed_classifier.v1 import classifier_pb2 as fast__typed__classifier_dot_v1_dot_classifier__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fast_typed_classifier/v1/classifier_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClassifierStub:
    """Typed-decision classification over text or JSON, backed by Laya checkpoints.

    Every question in a request is answered in the same forward pass. Concurrent requests
    (from any RPC below) are batched together on the server, so many small unary calls get
    the same GPU efficiency as one large batch.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Classify = channel.unary_unary(
                '/fast_typed_classifier.v1.Classifier/Classify',
                request_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.ClassifyBatch = channel.unary_unary(
                '/fast_typed_classifier.v1.Classifier/ClassifyBatch',
                request_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyBatchRequest.SerializeToString,
                response_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyBatchResponse.FromString,
                _registered_method=True)
        self.ClassifyStream = channel.stream_stream(
                '/fast_typed_classifier.v1.Classifier/ClassifyStream',
                request_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.Route = channel.unary_unary(
                '/fast_typed_classifier.v1.Classifier/Route',
                request_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.Routing.FromString,
                _registered_method=True)
        self.GetServerInfo = channel.unary_unary(
                '/fast_typed_classifier.v1.Classifier/GetServerInfo',
                request_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.GetServerInfoRequest.SerializeToString,
                response_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ServerInfo.FromString,
                _registered_method=True)


class ClassifierServicer:
    """Typed-decision classification over text or JSON, backed by Laya checkpoints.

    Every question in a request is answered in the same forward pass. Concurrent requests
    (from any RPC below) are batched together on the server, so many small unary calls get
    the same GPU efficiency as one large batch.
    """

    def Classify(self, request, context):
        """Classify one input.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyBatch(self, request, context):
        """Classify many inputs in one call. Responses keep request order. A failed item does not
        fail the call: its response carries `error` instead of answers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyStream(self, request_iterator, context):
        """Bidirectional stream for high-throughput clients. Each response is sent as soon as it is
        ready, not necessarily in request order: match responses by `request_id`. A failed item
        does not end the stream: its response carries `error`.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Route(self, request, context):
        """The routing decision only (which checkpoint would answer, and why). No forward pass.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerInfo(self, request, context):
        """Loaded checkpoints, device and batching limits.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClassifierServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Classify': grpc.unary_unary_rpc_method_handler(
                    servicer.Classify,
                    request_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.FromString,
                    response_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.SerializeToString,
            ),
            'ClassifyBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyBatch,
                    request_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyBatchRequest.FromString,
                    response_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyBatchResponse.SerializeToString,
            ),
            'ClassifyStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ClassifyStream,
                    request_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.FromString,
                    response_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.SerializeToString,
            ),
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.FromString,
                    response_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.Routing.SerializeToString,
            ),
            'GetServerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerInfo,
                    request_deserializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.GetServerInfoRequest.FromString,
                    response_serializer=fast__typed__classifier_dot_v1_dot_classifier__pb2.ServerInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fast_typed_classifier.v1.Classifier', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fast_typed_classifier.v1.Classifier', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Classifier:
    """Typed-decision classification over text or JSON, backed by Laya checkpoints.

    Every question in a request is answered in the same forward pass. Concurrent requests
    (from any RPC below) are batched together on the server, so many small unary calls get
    the same GPU efficiency as one large batch.
    """

    @staticmethod
    def Classify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fast_typed_classifier.v1.Classifier/Classify',
            fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.SerializeToString,
            fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fast_typed_classifier.v1.Classifier/ClassifyBatch',
            fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyBatchRequest.SerializeToString,
            fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fast_typed_classifier.v1.Classifier/ClassifyStream',
            fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.SerializeToString,
            fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fast_typed_classifier.v1.Classifier/Route',
            fast__typed__classifier_dot_v1_dot_classifier__pb2.ClassifyRequest.SerializeToString,
            fast__typed__classifier_dot_v1_dot_classifier__pb2.Routing.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fast_typed_classifier.v1.Classifier/GetServerInfo',
            fast__typed__classifier_dot_v1_dot_classifier__pb2.GetServerInfoRequest.SerializeToString,
            fast__typed__classifier_dot_v1_dot_classifier__pb2.ServerInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
